### ISSUE TITLE
CreateStreamRequest missing from client

### ISSUE THREAD

**Issue by sherzberg** [martinbaillie/go-graylog#1]
I'm still trying to figure out how the codegen works, but it appears the that client for interacting with CreateStreamRequest is missing?

Any ideas why?

**Comment by martinbaillie** [comment]
I've had a play around this morning trying a few different ways of generating the Swagger JSON/YAML, before feeding it to the Golang codegen, but no luck. I'm not sure why it skips over certain verbs

I've added a slightly different [Swagger spec](https://github.com/martinbaillie/go-graylog/blob/master/api/swagger-alternate.yaml) for reference, but at the moment it still results in the same missing code.

**Comment by martinbaillie** [comment]
Closing as stale
